source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

#base_url: http://vlandham.com
base_url: http://bioinfo/n/projects/jfv/biocore_reports
#base_url: /
description: ""

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.textile', 'new.rb', 'template.html']
